# Generated by Django 4.2 on 2023-04-15 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('nd_date', models.DateTimeField()),
                ('not_date', models.DateField()),
                ('s_date', models.DateTimeField(auto_now_add=True)),
                ('res_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resource')),
            ],
        ),
    ]
