# Generated by Django 4.2 on 2023-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nd_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='not_date',
            field=models.IntegerField(),
        ),
    ]
