# Generated by Django 4.2 on 2023-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_nd_date_alter_item_not_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='not_date',
            field=models.DateField(),
        ),
    ]
