# Generated by Django 4.2 on 2023-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_not_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nd_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='not_date',
            field=models.DateField(null=True),
        ),
    ]
