# Generated by Django 4.2 on 2023-04-15 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('resource_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('resource_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('top_tag', models.CharField(max_length=255)),
                ('bottom_tag', models.CharField(max_length=255)),
                ('title_cut', models.CharField(max_length=255)),
                ('date_cut', models.CharField(max_length=255)),
            ],
        ),
    ]
